#:import MDToolbar kivymd.uix.toolbar.MDToolbar
#:import utils kivy.utils
#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu
#:import MDRaisedButton kivymd.uix.button.MDRaisedButton

<HasilAkhir>:
    name: "hasilakhir"
    BoxLayout:
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        height:500
        width:300
        orientation: "vertical"
        # size_hint: self.width,self.height
        padding: 40, 0, 40, 150
        spacing: 50